name: roamkit_bbuem_apk
description: RoamKit managed-device Flutter app (Android / UEM managed config).
publish_to: "none"
version: 1.0.0+16

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  home_widget: 0.9.2+1
  unorm_dart: 0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
